language: java
install: mvn install -s support/settings.xml -DskipTests=true -P,-version
script: mvn test -s support/settings.xml -P,-version
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  irc: "irc.freenode.org#dynjs"
