language: java
install: mvn install -s support/settings.xml -DskipTests=true -DskipGitVersion=true
script: mvn test -s support/settings.xml -DskipGitVersion=true
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
notifications:
  irc: "irc.freenode.org#dynjs"
